# Playbook for helping to install Tendermint on remote servers

- name: Sync the service binary across to the servers
  synchronize:
    src: "{{ bin_path }}"
    dest: "{{ dest_path }}"

- name: Ensure correct service binary permissiones
  file:
    path: "{{ dest_path }}"
    mode: 0755
    owner: "{{ user }}"
    group: "{{ service }}"

- name: Delete any existing Tendermint configuration/data
  file: "path=/home/{{ user }}/.tendermint state=absent"
  when: copy_node_config == True

- name: Copy the Tendermint node